# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightcms', '0002_auto_20160603_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('path',)]),
        ),
    ]
