# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightcms', '0003_auto_20160603_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='blocks',
            field=models.ManyToManyField(to='lightcms.Block'),
        ),
        migrations.AddField(
            model_name='module',
            name='pages',
            field=models.ManyToManyField(to='lightcms.Page'),
        ),
    ]
