# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightcms', '0005_auto_20160603_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocks', models.ManyToManyField(to='lightcms.Block')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightcms.Module')),
                ('pages', models.ManyToManyField(to='lightcms.Page')),
            ],
        ),
    ]
