# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lightcms', '0006_modulerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
